spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/musicdb?useSSL=false
    username: prospring6
    password: prospring6
    pool-size: 30

logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
    level:
      root: INFO
      org.springframework.boot: INFO
      spring.examples.chapter06boot: INFO